POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"prueba3",
    "mail":"hidalgo11141@gmail.com",
    "password":"123456"

}


### login sin conexion a BDD


POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name":"prueba3",
    "mail":"hidalgo11141@gmail.com",
    "password":"123456"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoiZ3VhdGl0YTJAZ29rdS5jb20iLCJpZCI6MywiaWF0IjoxNzMzNzA1NjYzLCJleHAiOjE3MzM3MDkyNjN9.zpZTzF0DuvWGVULgDs-9ajV_jCuN1nmbHFdCh-Kuf2g