POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"prueba",
    "mail":"gf@gm.com",
    "password":"123456"

}


### login sin conexion a BDD
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name":"prueba",
    "mail":"gf@gm.com",
    "password":"123456"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer